version: '3.11.6'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=barandatlar
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
